// Prints a .env.local for the local stack: anon/service keys are JWTs signed
// with the LOCAL-ONLY secret used by scripts/local-stack/start.sh.
import crypto from "node:crypto";

const secret = process.env.LOCAL_JWT_SECRET ?? "local-development-jwt-secret-change-me-0123456789";
const b64 = (o) => Buffer.from(JSON.stringify(o)).toString("base64url");
const sign = (payload) => {
  const head = b64({ alg: "HS256", typ: "JWT" });
  const body = b64(payload);
  return `${head}.${body}.${crypto.createHmac("sha256", secret).update(`${head}.${body}`).digest("base64url")}`;
};
const exp = Math.floor(Date.now() / 1000) + 10 * 365 * 86400;
const db = process.argv[2] ?? "kora_dev";

console.log(`# Local development only — generated by scripts/local-stack/write-env.mjs. Never commit.
NEXT_PUBLIC_KORA_ENV=development
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${sign({ role: "anon", iss: "supabase-local", exp })}
SUPABASE_SERVICE_ROLE_KEY=${sign({ role: "service_role", iss: "supabase-local", exp })}
DATABASE_URL=postgres://kora_app:kora_app_local@localhost:5432/${db}
DATABASE_SSL=disable
CRON_SECRET=local-cron-secret-0123456789`);
