import { chromium } from "@playwright/test";
const S = "/tmp/claude-0/-home-user-Kora-Health/b182bebc-c307-5173-aa62-905e11a91aaa/scratchpad/shots";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on("console", (m) => m.type() === "error" && errors.push(m.text()));
page.on("pageerror", (e) => errors.push(String(e)));
const email = `patient-${Date.now()}@example.test`;
await page.goto("http://localhost:3000/sign-up");
await page.getByLabel("Your name").fill("Test Patient");
await page.getByLabel("Email").fill(email);
await page.getByLabel("Password").fill("Correct-Horse-9");
await page.getByLabel(/I agree/).check();
await page.getByRole("button", { name: "Create account" }).click();
await page.waitForURL("**/onboarding/patient", { timeout: 20000 });
console.log("onboarding reached");
await page.getByLabel("City", { exact: true }).fill("Toronto");
await page.getByRole("button", { name: "Finish setup" }).click();
await page.waitForURL("**/patient?welcome=1", { timeout: 20000 });
console.log("dashboard reached");
await page.screenshot({ path: `${S}/patient-dash.png`, fullPage: true });
await page.goto("http://localhost:3000/providers/amara-okafor-sample/request");
await page.locator('label:has(input[name="slot"])').first().click();
await page.getByLabel(/I understand/).check();
await page.getByRole("button", { name: "Send request" }).click();
await page.waitForURL("**/patient/appointments?requested=1", { timeout: 20000 });
console.log("request sent");
await page.screenshot({ path: `${S}/patient-appts.png`, fullPage: true });
console.log(JSON.stringify({ errors }));
await browser.close();
